# This script was generated by Taurus
from locust import HttpLocust, TaskSet, task
from gevent import sleep
import time

class UserBehaviour(TaskSet):
    @task(1)
    def generated_task(self):
        self.client.get(url="/")

class GeneratedSwarm(HttpLocust):
    task_set = UserBehaviour
    host = "http://blazedemo.com"
    min_wait = 0
    max_wait = 0

