FROM ubuntu:18.04

ENV DBUS_SESSION_BUS_ADDRESS=/dev/null DEBIAN_FRONTEND=noninteractive
ENV APT_INSTALL="apt-get -y install --no-install-recommends"

ADD https://dl-ssl.google.com/linux/linux_signing_key.pub /tmp
RUN apt-get -y update \
  && apt-get -y install dirmngr \
  && $APT_INSTALL software-properties-common apt-utils
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
  && cat /tmp/linux_signing_key.pub | apt-key add - \
  && apt-add-repository multiverse -y \
  && add-apt-repository ppa:git-core/ppa -y \
  && apt-add-repository ppa:yandex-load/main -y \
  && apt-add-repository ppa:nilarimogard/webupd8 -y
RUN $APT_INSTALL tzdata \
  && dpkg-reconfigure --frontend noninteractive tzdata \
RUN $APT_INSTALL language-pack-en mc kmod unzip build-essential libxslt1-dev libffi-dev libxi6 libgconf-2-4 libexif12 \
  && libyaml-dev udev openjdk-8-jdk xvfb siege tsung apache2-utils phantom phantom-ssl pepperflashplugin-nonfree \
  flashplugin-installer net-tools gcc-mingw-w64-x86-64 python3-dev python3-pip
RUN python3 -m pip install --upgrade pip setuptools wheel twine

RUN apt-get update \
  &&  apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common git \
  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
  && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
  && apt-get update \
  && apt-get install -y docker-ce docker-ce-cli containerd.io gcc-mingw-w64-x86-64 nsis libssl-dev \
  libncurses5-dev libsqlite3-dev libreadline-dev libtk8.5 libgdm-dev libdb4o-cil-dev libpcap-dev curl

RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" \
  && echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" >> /etc/apt/sources.list.d/google-cloud-sdk.list \
  && echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list \
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get update && apt-get install -y google-cloud-sdk kubectl

RUN apt-get clean