node {
    stage("clean") {
        // clean if needed
        // cleanWs()   // requires workspace cleanup plugin to be installed
        sh "pwd && ls -la"
    }
    
    stage("run test") {
        bzt "./examples/jmeter/stepping.yml -o settings.artifacts-dir=./artifacts"
    }

    stage("post-proc") {
	archiveArtifacts artifacts: 'artifacts/*.log'
	junit '**/junit.xml'
    }
}
