# coding=utf-8

import logging
import random
import string
import sys
import unittest
from time import time, sleep

import apiritif


class TestAPI(unittest.TestCase):

    def setUp(self):
        self.vars = {}

        timeout = 30.0
        apiritif.put_into_thread_store(timeout=timeout, func_mode=False, scenario_name='autogenerated_b448df0b11')

    def _1_httpblazedemocom(self):
        with apiritif.smart_transaction('http://blazedemo.com/'):
            response = apiritif.http.get('http://blazedemo.com/',
                                         cert=('certificate_file.pem', 'certificate-passphrase'))

    def test_test_requests(self):
        self._1_httpblazedemocom()
