# coding=utf-8

import logging
import random
import string
import sys
import unittest
from time import time, sleep

import apiritif


class TestAPI(unittest.TestCase):

    def setUp(self):
        self.vars = {}

        timeout = 30.0
        apiritif.put_into_thread_store(timeout=timeout, func_mode=False, scenario_name='autogenerated_87f1619977')

    def _1_apiritif(self):
        with apiritif.smart_transaction('apiritif'):
            response = apiritif.http.get('http://localhost:8000/')

    def test_test_requests(self):
        self._1_apiritif()
