# This script was generated by Taurus

from gevent import sleep
from re import findall, compile
from locust import HttpLocust, TaskSet, task, constant

class UserBehaviour(TaskSet):
    @task(1)
    def generated_task(self):
        self.client.get(timeout=30.0, url="http://blazedemo.com")
        

class GeneratedSwarm(HttpLocust):
    task_set = UserBehaviour
    host = ""
    wait_time = constant(0)

